{% set name = "captcha" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/captcha-{{ version }}.tar.gz
  sha256: 132cb5b9aafd1586bfa421c19f994f7b482873e7f981f80fff888954e02c35c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pillow
    - python >=3.6

test:
  imports:
    - captcha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lepture/captcha
  summary: A captcha library that generates audio and image CAPTCHAs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
