{% set name = "captcha" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/captcha-{{ version }}.tar.gz
  sha256: a1b462bcc633a64d8db5efa7754548a877c698d98f87716c620a707364cabd6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - captcha
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lepture/captcha
  summary: A captcha library that generates audio and image CAPTCHAs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
